# fly.toml app configuration file generated for timedify on 2024-12-19T12:00:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "timedify"
primary_region = "fra"

[build]

[deploy]
  # Migrates must pass; synthetic test is best-effort
  release_command = "sh -c 'npx prisma migrate deploy && ./scripts/synthetic-webhook-test.sh || echo \"Synthetic test skipped (non-blocking)\"'"

[env]
  PORT = "3000"
  NODE_ENV = "production"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
  
  # Verbesserte Load Balancing Konfiguration
  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  # Fly Deploy-Hook mit Health-Gate (optimiert)
  [[http_service.checks]]
    grace_period = "20s"
    interval = "10s"
    method = "GET"
    path = "/health"
    timeout = "2s"
    protocol = "http"
    tls_skip_verify = false

[processes]
  app = "npm run start"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
  processes = ["app"]
